services:

  app-container:
    build:
      dockerfile: /home/ubuntu/dockerComposeURL/Dockerfile
    ports:
      - "8000:80"

  nginx-container:
    build:
      context: .
      dockerfile: /home/ubuntu/dockerComposeURL/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app-container
